// <auto-generated />
using System;
using EnergyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706132522_MakeSmartPlugIntervalDataTimestampUnique")]
    partial class MakeSmartPlugIntervalDataTimestampUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsumptionApproach")
                        .HasColumnType("int");

                    b.Property<decimal?>("EuAnnualKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("EuLabelClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PowerPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("SelfMeasuredKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SelfMeasuredPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeviceId");

                    b.HasIndex("PowerPointId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.Property<Guid>("FlatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualKwhBaseline")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PlannedAnnualSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpikeThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(2.0m);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FlatId");

                    b.HasIndex("UserId");

                    b.ToTable("Flats", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ErrorCategory")
                        .HasColumnType("int");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GapNotifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ImportJobId");

                    b.HasIndex("FlatId");

                    b.ToTable("ImportJobs", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OriginalKwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ReadingDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReadingId");

                    b.HasIndex("FlatId", "ReadingDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MeterReadings_FlatId_ReadingDate");

                    b.ToTable("MeterReadings", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.Property<Guid>("PowerPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlugId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PowerPointId");

                    b.HasIndex("RoomId");

                    b.ToTable("PowerPoints", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("FlatId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugDailyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInterpolated")
                        .HasColumnType("bit");

                    b.Property<decimal>("KwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlatId", "PlugId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SmartPlugDailyData_FlatId_PlugId_Date");

                    b.ToTable("SmartPlugDailyData", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugIntervalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WhValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FlatId", "PlugId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SmartPlugIntervalData_FlatId_PlugId_Timestamp");

                    b.ToTable("SmartPlugIntervalData", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.Property<Guid>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ContractDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ContractStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MonthlyBaseFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TariffId");

                    b.HasIndex("FlatId", "ContractStartDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Tariffs_FlatId_ContractStartDate");

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ActiveFlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocaleOverride")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.PowerPoint", "PowerPoint")
                        .WithMany("Devices")
                        .HasForeignKey("PowerPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerPoint");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.ImportJob", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Room", "Room")
                        .WithMany("PowerPoints")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugDailyData", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugIntervalData", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.Navigation("PowerPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
