// <auto-generated />
using System;
using EnergyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702121947_MakeTariffEffectiveDateUnique")]
    partial class MakeTariffEffectiveDateUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.Property<Guid>("FlatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualKwhBaseline")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PlannedAnnualSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpikeThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(2.0m);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FlatId");

                    b.HasIndex("UserId");

                    b.ToTable("Flats", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OriginalKwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ReadingDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReadingId");

                    b.HasIndex("FlatId", "ReadingDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MeterReadings_FlatId_ReadingDate");

                    b.ToTable("MeterReadings", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.Property<Guid>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ContractDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ContractStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MonthlyBaseFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TariffId");

                    b.HasIndex("FlatId", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Tariffs_FlatId_EffectiveDate");

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocaleOverride")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });
#pragma warning restore 612, 618
        }
    }
}
