// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Tests.Data;

#nullable disable

namespace api.Tests.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteAppDbContext))]
    [Migration("20260802100534_AddInsightDismissal")]
    partial class AddInsightDismissal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsumptionApproach")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DecommissionedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EuAnnualKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("EuLabelClass")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("InUseSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PowerPointId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<decimal?>("SelfMeasuredKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SelfMeasuredPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("PowerPointId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.DeviceAssignmentPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PowerPointId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_DeviceAssignmentPeriods_DeviceId_OneOpenPeriod")
                        .HasFilter("[To] IS NULL");

                    b.HasIndex("DeviceId", "From")
                        .HasDatabaseName("IX_DeviceAssignmentPeriods_DeviceId_From");

                    b.ToTable("DeviceAssignmentPeriods", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.Property<Guid>("FlatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualKwhBaseline")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlannedAnnualSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<decimal>("SpikeThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(2.0m);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FlatId");

                    b.HasIndex("UserId");

                    b.ToTable("Flats", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorCategory")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GapNotifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImportJobId");

                    b.HasIndex("FlatId");

                    b.ToTable("ImportJobs", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Insight", b =>
                {
                    b.Property<Guid>("InsightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDismissed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("InsightId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RunId");

                    b.HasIndex("FlatId", "Type", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Insights_FlatId_Type_CreatedAt");

                    b.ToTable("Insights", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.InsightRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId");

                    b.HasIndex("FlatId")
                        .IsUnique()
                        .HasDatabaseName("IX_InsightRuns_FlatId_ActiveOnly")
                        .HasFilter("[Status] IN (0, 1)");

                    b.ToTable("InsightRuns", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OriginalKwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ReadingDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ReadingId");

                    b.HasIndex("FlatId", "ReadingDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MeterReadings_FlatId_ReadingDate");

                    b.ToTable("MeterReadings", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.Property<Guid>("PowerPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PowerPointId");

                    b.HasIndex("RoomId");

                    b.HasIndex("FlatId", "PlugId")
                        .IsUnique()
                        .HasDatabaseName("IX_PowerPoints_FlatId_PlugId_NotNull")
                        .HasFilter("[PlugId] IS NOT NULL");

                    b.ToTable("PowerPoints", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.HasIndex("FlatId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugDailyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInterpolated")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KwhValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlatId", "PlugId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_SmartPlugDailyData_FlatId_PlugId_Date");

                    b.ToTable("SmartPlugDailyData", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugIntervalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlugId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WhValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FlatId", "PlugId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_SmartPlugIntervalData_FlatId_PlugId_Timestamp");

                    b.ToTable("SmartPlugIntervalData", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.Property<Guid>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractDurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ContractStartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyBaseFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("TariffId");

                    b.HasIndex("FlatId", "ContractStartDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Tariffs_FlatId_ContractStartDate");

                    b.ToTable("Tariffs", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ActiveFlatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocaleOverride")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.PowerPoint", "PowerPoint")
                        .WithMany("Devices")
                        .HasForeignKey("PowerPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerPoint");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.DeviceAssignmentPeriod", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Flat", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.ImportJob", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Insight", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyTracker.Api.Data.Entities.InsightRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId");

                    b.Navigation("Device");

                    b.Navigation("Flat");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.InsightRun", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.MeterReading", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Room", "Room")
                        .WithMany("PowerPoints")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugDailyData", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.SmartPlugIntervalData", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Tariff", b =>
                {
                    b.HasOne("EnergyTracker.Api.Data.Entities.Flat", "Flat")
                        .WithMany()
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.PowerPoint", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("EnergyTracker.Api.Data.Entities.Room", b =>
                {
                    b.Navigation("PowerPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
