name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Restore dependencies
        run: dotnet restore EnergyTracker.sln

      - name: Build solution
        run: dotnet build EnergyTracker.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test EnergyTracker.sln --no-build --configuration Release